Feat/demographic attributes/jais13b
qcri/LLMeBench pull request #270
Opened 2024-02-03 06:04 UTC by firojalam

2024-06-02 10:54 UTC, MaramHasanain requested changes

2024-06-02 10:54 UTC, MaramHasanain commented on assets/ar/demographic_attributes/gender/ArabGend_Jais13b_ZeroShot.py
According to our results sheet, the score here is for JAIS with Arap-Tweet and not ArabGendDataset. Not sure which is correct, the asset or the results sheet. Need to refer to the results folder for this asset to check if we used this dataset or Araptweet

2024-06-03 08:49 UTC, firojalam commented on assets/ar/demographic_attributes/gender/ArabGend_Jais13b_ZeroShot.py
Unfortunately, the results in the sheet is wrong then. The results we have here ArabGendDataset is correct.

2025-02-27 07:15 UTC, MaramHasanain approved these changes

2025-02-27 07:15 UTC, MaramHasanain approved these changes

2025-02-27 07:16 UTC, merged